-- R-13 投资组合优化（FR-03-02）：组合优化运行与入选成员留痕

CREATE TABLE portfolio_run (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget           DECIMAL(24, 8) NOT NULL,
    max_count        INT,
    candidate_count  INT          NOT NULL,
    total_npv        DECIMAL(24, 8),
    total_investment DECIMAL(24, 8),
    explanation      VARCHAR(2000),
    frontier_json    VARCHAR(8000),
    engine_version   VARCHAR(64)  NOT NULL,
    created_by       VARCHAR(64),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE portfolio_member (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id           BIGINT       NOT NULL,
    scenario_id      BIGINT       NOT NULL,
    scenario_name    VARCHAR(255) NOT NULL,
    project_name     VARCHAR(255),
    npv              DECIMAL(24, 8),
    investment       DECIMAL(24, 8),
    irr              DECIMAL(24, 8),
    selected         BOOLEAN      NOT NULL DEFAULT FALSE,
    rank_no          INT
);

CREATE INDEX idx_portfolio_member_run ON portfolio_member(run_id);
