-- R-14 BPM 可配置审批流（FR-04-03）：流程定义 + 节点定义，现有固定三段链作为默认模板入库

CREATE TABLE approval_flow_def (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(64)  NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE approval_node_def (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flow_def_id     BIGINT      NOT NULL,
    node_code       VARCHAR(64) NOT NULL,
    node_name       VARCHAR(255) NOT NULL,
    seq             INT         NOT NULL,
    approver_role   VARCHAR(64) NOT NULL,
    condition_expr  VARCHAR(1000),
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_approval_node_flow ON approval_node_def(flow_def_id);

ALTER TABLE approval_instance ADD COLUMN flow_def_id BIGINT;

-- 默认模板：现有固定三段链（提交 → 财务复核 → 项目经理审批）
INSERT INTO approval_flow_def (code, name, description, is_default, enabled)
VALUES ('DEFAULT_REVIEW_CHAIN', '默认三段审批链', 'M1 固定审批链迁移入库：提交 → 财务复核 → 项目经理审批。', TRUE, TRUE);

INSERT INTO approval_node_def (flow_def_id, node_code, node_name, seq, approver_role, condition_expr)
SELECT id, 'REVIEW', '财务复核', 1, 'FINANCE_SPECIALIST', NULL FROM approval_flow_def WHERE code = 'DEFAULT_REVIEW_CHAIN';
INSERT INTO approval_node_def (flow_def_id, node_code, node_name, seq, approver_role, condition_expr)
SELECT id, 'APPROVAL', '项目经理审批', 2, 'PROJECT_MANAGER', NULL FROM approval_flow_def WHERE code = 'DEFAULT_REVIEW_CHAIN';
