-- R-15 协同编辑实时化（FR-04-02）：评论（@提及）+ 变更时间线（版本递增）+ 在线状态

CREATE TABLE scenario_comment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id  BIGINT       NOT NULL,
    parent_id    BIGINT,
    content      VARCHAR(2000) NOT NULL,
    mentions     VARCHAR(500),              -- @提及的用户名列表（逗号分隔，解析自 content）
    author_id    BIGINT,
    author_name  VARCHAR(64)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_comment_scenario ON scenario_comment(scenario_id);

CREATE TABLE scenario_change (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id  BIGINT       NOT NULL,
    version_no   INT          NOT NULL,      -- 方案内递增 v1, v2, ...
    change_type  VARCHAR(32)  NOT NULL,      -- FIELD_UPDATED / LOCK_ACQUIRED / LOCK_RELEASED / COMMENT_ADDED / CALCULATION_RUN / APPROVAL_ACTION
    field_name   VARCHAR(64),
    old_value    VARCHAR(1000),
    new_value    VARCHAR(1000),
    operator_id  BIGINT,
    operator_name VARCHAR(64) NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_change_scenario ON scenario_change(scenario_id, version_no);

CREATE TABLE scenario_presence (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id  BIGINT       NOT NULL,
    user_id      BIGINT       NOT NULL,
    user_name    VARCHAR(64)  NOT NULL,
    last_seen_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_presence_scenario_user UNIQUE (scenario_id, user_id)
);
