-- R-16 项目库与知识沉淀（FR-03-03）：标签表 + 已投运项目复盘（计划 vs 实际）

CREATE TABLE project_tag (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT      NOT NULL,
    tag        VARCHAR(64) NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_project_tag UNIQUE (project_id, tag)
);

CREATE INDEX idx_project_tag_tag ON project_tag(tag);

CREATE TABLE project_review (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id            BIGINT       NOT NULL UNIQUE,   -- 一项目一份复盘
    scenario_id           BIGINT,                          -- 对照的测算方案（取计划指标）
    actual_npv            DECIMAL(24, 8),
    actual_irr            DECIMAL(24, 8),
    actual_investment     DECIMAL(24, 8),
    actual_payback_years  DECIMAL(10, 4),
    operation_start_date  DATE,
    lessons               VARCHAR(2000),                   -- 经验教训
    created_by            VARCHAR(64),
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
