-- R-17 AI 决策引擎（FR-05）：历史运营数据库 + 模型版本表

CREATE TABLE ai_operation_record (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        BIGINT       NOT NULL,
    period            VARCHAR(16)  NOT NULL,        -- 如 2025-Q2 / 2025
    actual_revenue    DECIMAL(24, 8),
    actual_cost       DECIMAL(24, 8),
    actual_output     DECIMAL(24, 8),
    actual_npv        DECIMAL(24, 8),
    actual_irr        DECIMAL(24, 8),
    deviation_ratio   DECIMAL(10, 6),               -- 与计划口径的偏差率（录入或计算）
    verified          BOOLEAN      NOT NULL DEFAULT FALSE,  -- 校验后才入训练库
    note              VARCHAR(1000),
    created_by        VARCHAR(64),
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ai_op_project ON ai_operation_record(project_id);
CREATE INDEX idx_ai_op_verified ON ai_operation_record(verified);

CREATE TABLE ai_model_version (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_code      VARCHAR(64)  NOT NULL UNIQUE,
    model_name      VARCHAR(255) NOT NULL,
    version         VARCHAR(32)  NOT NULL,
    algorithm       VARCHAR(255) NOT NULL,          -- 算法说明（可解释性要求）
    weights_json    VARCHAR(2000),                  -- 打分权重配置
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 默认打分模型：六因子加权（可解释，不替代人工决策）
INSERT INTO ai_model_version (model_code, model_name, version, algorithm, weights_json, active)
VALUES ('SCORING_V1', '投资方案六因子打分模型', '1.0.0',
        '规则化加权评分：NPV 正向、IRR 相对 WACC 溢价、静态回收期、敏感性最高等级、盈亏平衡产能利用率、历史复盘偏差率六因子加权求和；阈值 ≥70 建议立项，50~70 谨慎推进，<50 建议暂缓。因子得分与权重全量输出，保证可解释、不替代人工决策。',
        '{"npv":0.25,"irrSpread":0.25,"payback":0.15,"sensitivity":0.15,"bepUtilization":0.10,"reviewDeviation":0.10}',
        TRUE);
