-- R-15 收尾：字段级锁定与冲突合并（FR-04-02 约束"编辑冲突需有合并/锁定机制"）

CREATE TABLE scenario_field_lock (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id  BIGINT       NOT NULL,
    field_key    VARCHAR(128) NOT NULL,      -- 字段标识：param.wacc / investment.amount:3 / cost.amount:5 / financing.ratio:2
    holder_id    BIGINT,
    holder_name  VARCHAR(64)  NOT NULL,
    acquired_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expire_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uk_field_lock_scenario_field UNIQUE (scenario_id, field_key)
);

CREATE INDEX idx_field_lock_scenario ON scenario_field_lock(scenario_id);
