CREATE TABLE sys_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64)  NOT NULL UNIQUE,
    password_hash   VARCHAR(200) NOT NULL,
    display_name    VARCHAR(100) NOT NULL,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(64)  NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL
);

CREATE TABLE sys_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE project (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(64)  NOT NULL UNIQUE,
    name            VARCHAR(200) NOT NULL,
    project_type    VARCHAR(64),
    status          VARCHAR(32)  NOT NULL DEFAULT 'DRAFT',
    department      VARCHAR(100),
    owner_id        BIGINT,
    tags            VARCHAR(500),
    description     VARCHAR(1000),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE scenario (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT       NOT NULL,
    name            VARCHAR(200) NOT NULL,
    version_no      INT          NOT NULL DEFAULT 1,
    status          VARCHAR(32)  NOT NULL DEFAULT 'DRAFT',
    horizon_years   INT          NOT NULL DEFAULT 10,
    construction_years INT       NOT NULL DEFAULT 2,
    remarks         VARCHAR(1000),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE parameter_set (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id         BIGINT         NOT NULL UNIQUE,
    wacc                DECIMAL(12, 8) NOT NULL,
    wacc_source         VARCHAR(200),
    tax_rate            DECIMAL(12, 8) NOT NULL DEFAULT 0.25,
    depreciation_years  INT            NOT NULL DEFAULT 10,
    residual_rate       DECIMAL(12, 8) NOT NULL DEFAULT 0.05,
    loan_ratio_limit    DECIMAL(12, 8) NOT NULL DEFAULT 0.70,
    price_per_unit      DECIMAL(18, 4) NOT NULL DEFAULT 0,
    unit_cost           DECIMAL(18, 4) NOT NULL DEFAULT 0,
    annual_output       DECIMAL(18, 4) NOT NULL DEFAULT 0,
    fixed_operating_cost DECIMAL(18, 4) NOT NULL DEFAULT 0,
    formula_version     VARCHAR(64),
    created_at          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE investment_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id     BIGINT         NOT NULL,
    category        VARCHAR(64)    NOT NULL,
    name            VARCHAR(200)   NOT NULL,
    amount          DECIMAL(18, 4) NOT NULL,
    year_no         INT            NOT NULL DEFAULT 0
);

CREATE TABLE financing_plan (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id     BIGINT         NOT NULL,
    source_type     VARCHAR(64)    NOT NULL,
    ratio           DECIMAL(12, 8) NOT NULL,
    amount          DECIMAL(18, 4) NOT NULL,
    interest_rate   DECIMAL(12, 8) NOT NULL DEFAULT 0,
    term_years      INT            NOT NULL DEFAULT 0
);

CREATE TABLE calculation_task (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id     BIGINT       NOT NULL,
    task_type       VARCHAR(32)  NOT NULL,
    status          VARCHAR(32)  NOT NULL,
    progress        INT          NOT NULL DEFAULT 0,
    request_key     VARCHAR(100),
    error_message   VARCHAR(2000),
    created_by      BIGINT,
    started_at      TIMESTAMP,
    finished_at     TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cash_flow_row (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id     BIGINT         NOT NULL,
    task_id         BIGINT         NOT NULL,
    statement_type  VARCHAR(64)    NOT NULL,
    period_no       INT            NOT NULL,
    inflow          DECIMAL(18, 4) NOT NULL DEFAULT 0,
    outflow         DECIMAL(18, 4) NOT NULL DEFAULT 0,
    net_cash_flow   DECIMAL(18, 4) NOT NULL DEFAULT 0,
    discounted_cf   DECIMAL(18, 4) NOT NULL DEFAULT 0,
    cumulative_cf   DECIMAL(18, 4) NOT NULL DEFAULT 0
);

CREATE TABLE calculation_result (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id     BIGINT         NOT NULL,
    task_id         BIGINT         NOT NULL,
    metric_code     VARCHAR(64)    NOT NULL,
    metric_value    DECIMAL(24, 8) NOT NULL,
    formula_version VARCHAR(64)    NOT NULL,
    engine_version  VARCHAR(64)    NOT NULL,
    parameter_set_id BIGINT,
    input_hash      VARCHAR(128),
    calculated_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE report_document (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id     BIGINT       NOT NULL,
    task_id         BIGINT,
    title           VARCHAR(200) NOT NULL,
    file_path       VARCHAR(500) NOT NULL,
    file_type       VARCHAR(32)  NOT NULL,
    status          VARCHAR(32)  NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE approval_instance (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id     BIGINT       NOT NULL,
    status          VARCHAR(32)  NOT NULL,
    current_node    VARCHAR(32)  NOT NULL,
    submitted_by    BIGINT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE approval_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id     BIGINT       NOT NULL,
    node_code       VARCHAR(32)  NOT NULL,
    decision        VARCHAR(32)  NOT NULL,
    comment_text    VARCHAR(1000),
    operator_id     BIGINT,
    operated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE edit_lock (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id     BIGINT       NOT NULL UNIQUE,
    holder_id       BIGINT       NOT NULL,
    holder_name     VARCHAR(100) NOT NULL,
    expire_at       TIMESTAMP    NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id        BIGINT,
    actor_name      VARCHAR(100),
    action          VARCHAR(64)  NOT NULL,
    target_type     VARCHAR(64)  NOT NULL,
    target_id       VARCHAR(64),
    before_value    CLOB,
    after_value     CLOB,
    trace_id        VARCHAR(64),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE import_job (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id     BIGINT       NOT NULL,
    file_name       VARCHAR(255) NOT NULL,
    status          VARCHAR(32)  NOT NULL,
    message         VARCHAR(2000),
    created_by      BIGINT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at     TIMESTAMP
);

CREATE INDEX idx_scenario_project ON scenario(project_id);
CREATE INDEX idx_task_status ON calculation_task(status);
CREATE INDEX idx_cashflow_scenario ON cash_flow_row(scenario_id, statement_type);
CREATE INDEX idx_result_scenario ON calculation_result(scenario_id);
CREATE INDEX idx_audit_created ON audit_event(created_at);
