-- ============================================================
-- V4__financial_engine_upgrade.sql
-- R-01: 财务引擎重写配套数据模型扩展（FR-01-01/02/04）
-- 兼容 H2 / PostgreSQL
-- ============================================================

-- 1) 投资估算三级树 --------------------------------------------------
ALTER TABLE investment_item ADD COLUMN item_code  VARCHAR(32);
ALTER TABLE investment_item ADD COLUMN parent_id  BIGINT;
ALTER TABLE investment_item ADD COLUMN sort_order INT NOT NULL DEFAULT 0;
CREATE INDEX idx_investment_item_scenario ON investment_item(scenario_id);

-- 2) 成本费用分项 ----------------------------------------------------
CREATE TABLE cost_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id     BIGINT         NOT NULL,
    category        VARCHAR(64)    NOT NULL,   -- RAW_MATERIAL / LABOR_MANUFACTURING / OTHER_OPERATING
    name            VARCHAR(200)   NOT NULL,
    year_no         INT            NOT NULL,   -- 0 表示达产年默认值；>0 表示该运营年覆盖值
    amount          DECIMAL(18, 4) NOT NULL,
    created_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_cost_item_scenario ON cost_item(scenario_id, category, year_no);

-- 3) 参数集扩展：折旧政策 / 摊销 / 还款 / 税率梯度 / 投产负荷 ----------
ALTER TABLE parameter_set ADD COLUMN depreciation_policy VARCHAR(32) NOT NULL DEFAULT 'STRAIGHT_LINE';
ALTER TABLE parameter_set ADD COLUMN amortization_years  INT NOT NULL DEFAULT 0;          -- 0 = 无摊销
ALTER TABLE parameter_set ADD COLUMN amortizable_amount  DECIMAL(18, 4) NOT NULL DEFAULT 0; -- 无形资产等摊销基数
ALTER TABLE parameter_set ADD COLUMN repayment_method    VARCHAR(32) NOT NULL DEFAULT 'EQUAL_PRINCIPAL';
ALTER TABLE parameter_set ADD COLUMN tax_schedule        CLOB;        -- JSON：[{"fromYear":1,"toYear":3,"rate":0},{"fromYear":4,"toYear":6,"rate":0.125}]
ALTER TABLE parameter_set ADD COLUMN ramp_up             CLOB;        -- JSON：[{"year":1,"loadFactor":0.8}]，未列年份默认 1.0

-- 4) 融资方案扩展：还款方式 / 宽限期 ---------------------------------
ALTER TABLE financing_plan ADD COLUMN repayment_method VARCHAR(32) NOT NULL DEFAULT 'EQUAL_PRINCIPAL';
ALTER TABLE financing_plan ADD COLUMN grace_years      INT NOT NULL DEFAULT 0;  -- 宽限期内只付息

-- 5) 现金流行扩展：利润与成本分解（供报表与瀑布图直接取数） ------------
ALTER TABLE cash_flow_row ADD COLUMN revenue        DECIMAL(18, 4) NOT NULL DEFAULT 0;
ALTER TABLE cash_flow_row ADD COLUMN operating_cost DECIMAL(18, 4) NOT NULL DEFAULT 0;
ALTER TABLE cash_flow_row ADD COLUMN depreciation   DECIMAL(18, 4) NOT NULL DEFAULT 0;
ALTER TABLE cash_flow_row ADD COLUMN amortization   DECIMAL(18, 4) NOT NULL DEFAULT 0;
ALTER TABLE cash_flow_row ADD COLUMN interest       DECIMAL(18, 4) NOT NULL DEFAULT 0;
ALTER TABLE cash_flow_row ADD COLUMN tax            DECIMAL(18, 4) NOT NULL DEFAULT 0;
ALTER TABLE cash_flow_row ADD COLUMN net_profit     DECIMAL(18, 4) NOT NULL DEFAULT 0;
