-- ============================================================
-- V5__sensitivity_analysis.sql
-- R-04: 敏感性分析（FR-02-01）运行与单元格留痕
-- 兼容 H2 / PostgreSQL
-- ============================================================

CREATE TABLE sensitivity_run (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id    BIGINT       NOT NULL,
    task_id        BIGINT,                       -- 关联的基准测算任务（可选）
    target_metric  VARCHAR(64)  NOT NULL,        -- 目标指标，默认 NPV
    variable1      VARCHAR(32)  NOT NULL,        -- 因素1：PRICE/UNIT_COST/INVESTMENT/CONSTRUCTION_PERIOD
    range1         DECIMAL(8,4) NOT NULL,        -- 波动区间（±）
    steps1         INT          NOT NULL,        -- 步数（奇数，含基准）
    variable2      VARCHAR(32),                  -- 因素2（可空=单因素）
    range2         DECIMAL(8,4),
    steps2         INT,
    base_value     DECIMAL(24,8),                -- 基准方案目标指标值
    status         VARCHAR(32)  NOT NULL,        -- SUCCESS/FAILED
    error_message  VARCHAR(2000),
    engine_version VARCHAR(64)  NOT NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_sensitivity_run_scenario ON sensitivity_run(scenario_id);

CREATE TABLE sensitivity_cell (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id       BIGINT       NOT NULL,
    factor1      DECIMAL(12,8) NOT NULL,         -- 因素1 波动比例（如 -0.20）
    factor2      DECIMAL(12,8),                  -- 因素2 波动比例（单因素为 null）
    metric_value DECIMAL(24,8) NOT NULL,         -- 该组合下目标指标值
    CONSTRAINT fk_sensitivity_cell_run FOREIGN KEY (run_id) REFERENCES sensitivity_run (id) ON DELETE CASCADE
);
CREATE INDEX idx_sensitivity_cell_run ON sensitivity_cell(run_id);
