-- R-09 目标反算（FR-01-05）：反算运行记录（结果 JSON 存 solved/factor/达成值/说明等）

CREATE TABLE reverse_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id     BIGINT       NOT NULL,
    task_id         BIGINT,
    target_metric   VARCHAR(32)  NOT NULL,
    target_value    DECIMAL(24, 8) NOT NULL,
    variable        VARCHAR(32)  NOT NULL,
    factor          DECIMAL(24, 8),
    solved_value    DECIMAL(24, 8),
    base_value      DECIMAL(24, 8),
    achieved_value  DECIMAL(24, 8),
    feasible        BOOLEAN      NOT NULL DEFAULT FALSE,
    iterations      INT          NOT NULL DEFAULT 0,
    sensitivity_note VARCHAR(1000),
    boundary_note   VARCHAR(2000),
    engine_version  VARCHAR(64)  NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_reverse_scenario ON reverse_run(scenario_id);
