-- R-11 蒙特卡洛概率分析（FR-02-03）：抽样运行记录（红线 R11：随机种子必须入库，结果可复现）

CREATE TABLE monte_carlo_run (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id      BIGINT       NOT NULL,
    task_id          BIGINT,
    target_metric    VARCHAR(32)  NOT NULL,
    iterations       INT          NOT NULL,
    seed             BIGINT       NOT NULL,
    variables_json   VARCHAR(4000) NOT NULL,
    mean_value       DECIMAL(24, 8),
    std_dev          DECIMAL(24, 8),
    prob_positive    DECIMAL(10, 6),
    var95            DECIMAL(24, 8),
    p5               DECIMAL(24, 8),
    p50              DECIMAL(24, 8),
    p95              DECIMAL(24, 8),
    min_value        DECIMAL(24, 8),
    max_value        DECIMAL(24, 8),
    histogram_json   VARCHAR(8000),
    cumulative_json  VARCHAR(8000),
    engine_version   VARCHAR(64)  NOT NULL,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_montecarlo_scenario ON monte_carlo_run(scenario_id);
