-- R-12 智能风险预警（FR-02-04）：阈值规则 + 预警事件留痕

CREATE TABLE risk_rule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_code     VARCHAR(32)  NOT NULL,
    direction       VARCHAR(8)   NOT NULL,           -- BELOW: 指标低于阈值触发; ABOVE: 高于阈值触发
    threshold_value DECIMAL(24, 8) NOT NULL,
    level           VARCHAR(8)   NOT NULL,           -- RED / YELLOW
    strategy        VARCHAR(1000),                   -- 策略建议
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_by      VARCHAR(64),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_risk_rule_metric ON risk_rule(metric_code);

CREATE TABLE risk_alert_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id         BIGINT       NOT NULL,
    scenario_id     BIGINT       NOT NULL,
    task_id         BIGINT,
    metric_code     VARCHAR(32)  NOT NULL,
    metric_value    DECIMAL(24, 8) NOT NULL,
    threshold_value DECIMAL(24, 8) NOT NULL,
    level           VARCHAR(8)   NOT NULL,
    message         VARCHAR(1000) NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'OPEN',  -- OPEN / ACKED / RECOVERED
    ack_by          VARCHAR(64),
    ack_at          TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_risk_alert_status ON risk_alert_event(status);
CREATE INDEX idx_risk_alert_scenario ON risk_alert_event(scenario_id);
CREATE INDEX idx_risk_alert_rule ON risk_alert_event(rule_id);

-- 默认规则种子（与 R-07 仪表盘占位规则一致的口径：IRR 低于 8% 红灯、低于 10% 黄灯）
INSERT INTO risk_rule (metric_code, direction, threshold_value, level, strategy, enabled, created_by)
VALUES ('IRR', 'BELOW', 0.08, 'RED', 'IRR 低于 8% 资金成本基准：建议重新评估投资规模与售价假设，或暂缓立项。', TRUE, 'system');
INSERT INTO risk_rule (metric_code, direction, threshold_value, level, strategy, enabled, created_by)
VALUES ('IRR', 'BELOW', 0.10, 'YELLOW', 'IRR 接近基准下限：建议关注售价与成本敏感性，准备风险应对预案。', TRUE, 'system');
INSERT INTO risk_rule (metric_code, direction, threshold_value, level, strategy, enabled, created_by)
VALUES ('NPV', 'BELOW', 0, 'RED', 'NPV 为负：项目在基准折现率下不创造价值，建议优化方案或放弃。', TRUE, 'system');
