spring:
  datasource:
    url: jdbc:h2:mem:iids;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

iids:
  worker:
    enabled: true
    poll-ms: 500
